local_configs:
  server:
    port: 8080
    host: "0.0.0.0"

  database:
    host: "db" #only in docker, change to localhost when needed
    port: "5432"
    name: "postgres"
    user: "postgres"
    schema: "public"
    password: "postgres"